### ISSUE TITLE
update pip

### ISSUE THREAD

**Issue by hoggatt** [pragmatic-streamlit/streamlit-file-browser#26]
Hi, it looks like you've made many updates but the latest version on[ pip is 1.0.4](https://pypi.org/project/streamlit-file-browser/). Are you able to update it so the newest version can be used? 

Thank you! This project looks awesome.

**Comment by y805939188** [comment]
> Hi, it looks like you've made many updates but the latest version on[ pip is 1.0.4](https://pypi.org/project/streamlit-file-browser/). Are you able to update it so the newest version can be used?
> 
> Thank you! This project looks awesome.

@hoggatt  Hi. I have uploaded the latest version to pip (https://pypi.org/project/streamlit-file-browser/3.2.3/), now you can try to install it.
