### ISSUE TITLE
File browser is cut off in my application

### ISSUE THREAD

**Issue by 123kyle16** [pragmatic-streamlit/streamlit-file-browser#37]
Whenever I try to use the HTTP server provided as an example it is cut off. When I use different servers it seems to fill out all the way. See screenshot
<img width="1608" alt="Screenshot 2024-05-21 at 6 45 26 PM" src="https://github.com/pragmatic-streamlit/streamlit-file-browser/assets/136383523/a32588e8-2d32-44c9-9bd8-38f6659ea432">

**Comment by y805939188** [comment]
> Whenever I try to use the HTTP server provided as an example it is cut off. When I use different servers it seems to fill out all the way. See screenshot <img alt="Screenshot 2024-05-21 at 6 45 26 PM" width="1608" src="https://private-user-images.githubusercontent.com/136383523/332618727-a32588e8-2d32-44c9-9bd8-38f6659ea432.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzODIwNDMsIm5iZiI6MTcxNjM4MTc0MywicGF0aCI6Ii8xMzYzODM1MjMvMzMyNjE4NzI3LWEzMjU4OGU4LTJkMzItNDRjOS05YmQ4LTM4ZjY2NTllYTQzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQxMjQyMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDRjZDExNjg4M2Q3ZTgwNGVlYWQ0MDAzNzgxZDg2YzMxZTc1MTExYjVmNjhjOWE3OWRjYTBhZTczZTJkZGE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GVyg6fkbDbAPQ4OQjuJzHOVR4IiFVJfk38GtQmVX5Mo">

Hi, I didn't quite understand the problem you encountered. Can you describe it more clearly or provide a way to reproduce it?

**Comment by 123kyle16** [comment]
Sorry! 

So I have the following code: 

`import streamlit as st
from streamlit_file_browser import st_file_browser
st.set_page_config(layout='wide')


st_file_browser('./',
    key="deep1",
    use_static_file_server=True,
    show_choose_file=True,
    show_delete_file=True,
    show_download_file=False,
    show_new_folder=True,
    show_upload_file=True,
    static_file_server_path='http://localhost:8000',
)`

I then use `python3 -m streamlit run tester.py`
The result is the screenshot
<img width="1608" alt="Screenshot 2024-05-22 at 10 03 30 AM" src="https://github.com/pragmatic-streamlit/streamlit-file-browser/assets/136383523/5bb8ad35-29e3-4a69-b443-68295c57433d">

The server I am using is the HTML server you linked to at the bottom of the github. The HTML server looks like this when I directly access it at http://localhost:8000


<img width="1728" alt="Screenshot 2024-05-22 at 10 04 22 AM" src="https://github.com/pragmatic-streamlit/streamlit-file-browser/assets/136383523/b2470062-6b03-4ece-8f8f-3454f398fd6e">


In the HTML server when I directly access it I can see the whole webpage, but when its in the streamlit filebrowser I can no longer see the entire page and it will not let me scroll down.

**Comment by y805939188** [comment]
> Sorry!
> 
> So I have the following code:
> 
> `import streamlit as st from streamlit_file_browser import st_file_browser st.set_page_config(layout='wide')
> 
> st_file_browser('./', key="deep1", use_static_file_server=True, show_choose_file=True, show_delete_file=True, show_download_file=False, show_new_folder=True, show_upload_file=True, static_file_server_path='http://localhost:8000', )`
> 
> I then use `python3 -m streamlit run tester.py` The result is the screenshot <img alt="Screenshot 2024-05-22 at 10 03 30 AM" width="1608" src="https://private-user-images.githubusercontent.com/136383523/332872551-5bb8ad35-29e3-4a69-b443-68295c57433d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NDkxMDUsIm5iZiI6MTcxNjQ0ODgwNSwicGF0aCI6Ii8xMzYzODM1MjMvMzMyODcyNTUxLTViYjhhZDM1LTI5ZTMtNGE2OS1iNDQzLTY4Mjk1YzU3NDMzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QwNzIwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTllM2QzNjU3ODM5M2UzNjc1N2IyNWZhMWQyYTA3YjkxMDc2NjYzODliNGJlMmE0MzU0NWU2NTVhNDJhYTM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WnqUiQMKouZgvVps6Ix0M4YhDVMvdCrNM5kw4XaPruA">
> 
> The server I am using is the HTML server you linked to at the bottom of the github. The HTML server looks like this when I directly access it at http://localhost:8000
> 
> <img alt="Screenshot 2024-05-22 at 10 04 22 AM" width="1728" src="https://private-user-images.githubusercontent.com/136383523/332872808-b2470062-6b03-4ece-8f8f-3454f398fd6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NDkxMDUsIm5iZiI6MTcxNjQ0ODgwNSwicGF0aCI6Ii8xMzYzODM1MjMvMzMyODcyODA4LWIyNDcwMDYyLTZiMDMtNGVjZS04ZjhmLTM0NTRmMzk4ZmQ2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QwNzIwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzgzZTJmYmJhZmU5MWZhMzdkYjdjOThhZDcwY2UyNGRmYWE1Yzc2NDI4MmY3ZjJmODRiMzVjYjIyNmNjOWQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-G_D-8kvGvq0djCYPYjPD2NvBFgv_eY5ZJWUqhv_Czg">
> In the HTML server when I directly access it I can see the whole webpage, but when its in the streamlit filebrowser I can no longer see the entire page and it will not let me scroll down.

Ok I see. The reason is that I forked the `gohttpserver` repository a long time ago and made abundant modifications to it. However, I forgot to update the README. So if you install this `gohttpserver` according to the old README, you would install the original version. Now, if you want to use the `gohttpserver` and you are going to test it on macOS (M1), you can execute an extra command: `./example_artifacts/static_file_server/gohttpserver -r ./ -p 8000`. This will run a local HTTP file server.
![iWSgJIBbwQ](https://github.com/pragmatic-streamlit/streamlit-file-browser/assets/28889103/558ebfda-5bf4-46cd-be36-8c87285abb17)
```python
import streamlit as st
    from streamlit_file_browser import st_file_browser
    st.set_page_config(layout='wide')

    st_file_browser('./',
        key="deep1",
        use_static_file_server=True,
        show_choose_file=True,
        show_delete_file=True,
        show_download_file=False,
        show_new_folder=True,
        show_upload_file=True,
        static_file_server_path='http://localhost:8000',
    )
```
It will run well:
<img width="1861" alt="image" src="https://github.com/pragmatic-streamlit/streamlit-file-browser/assets/28889103/53e373ba-d4ad-4178-ba49-f75f444808b1">

And then, if you want to run this static file server on Ubuntu or other systems, you can use cross-compilation with Golang.
Thank you feedback.

**Comment by 123kyle16** [comment]
Got it!

**Comment by 123kyle16** [comment]
How do I use the windows version? I am happy to download the original version, but will that have the same features as the macos  (M1) one?
