### ISSUE TITLE
Upload option not working and is dark mode available?

### ISSUE THREAD

**Issue by 123kyle16** [pragmatic-streamlit/streamlit-file-browser#38]
Hello again! I was able to resolve the previous issue on my application.

But, when I run the command ./static_file_server/gohttpserver -r ./static/static/examples -p 8000 --upload
 I do not see the upload option. Screenshot shows. 
![Screenshot 2024-05-28 at 5 14 22 PM](https://github.com/pragmatic-streamlit/streamlit-file-browser/assets/136383523/7e79b3eb-ecae-4b5b-8675-342f3cd8e063)

I am using the following code 

show_preview=st.checkbox('Preview',key='Examples')
event_example = st_file_browser('./static/static',
    key="deep1",
    show_preview=show_preview,
    use_static_file_server=True,
    show_choose_file=True,
    show_delete_file=True,
    show_download_file=False,
    show_new_folder=True,
    show_upload_file=True,
    static_file_server_path='http://localhost:8000'
)

**Comment by 123kyle16** [comment]
oh also, is there a way to change the theme of the server? I would like it to match my app

**Comment by 123kyle16** [comment]
Oh, also, is there an option to include a refresh button? When I manually add a file to the directory I have to reset the component in streamlit. I usually click the back button and then go back into the folder and the file appears

**Comment by y805939188** [comment]
> Hello again! I was able to resolve the previous issue on my application.
> 
> But, when I run the command ./static_file_server/gohttpserver -r ./static/static/examples -p 8000 --upload I do not see the upload option. Screenshot shows. ![Screenshot 2024-05-28 at 5 14 22 PM](https://private-user-images.githubusercontent.com/136383523/334598527-7e79b3eb-ecae-4b5b-8675-342f3cd8e063.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5Njc0NTgsIm5iZiI6MTcxNjk2NzE1OCwicGF0aCI6Ii8xMzYzODM1MjMvMzM0NTk4NTI3LTdlNzliM2ViLWVjYWUtNGI1Yi04Njc1LTM0MmYzY2Q4ZTA2My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOVQwNzE5MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MmM2ZDM0MmU5NjBjZTQzYmY2NmUyZDQyODFkZDJjMWJmN2JkNzI0NmZlZjVmZjUzNmJjZTliMTFiMTM3Zjg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5mVWCILmSPAMhG5kxpQG68ShUeH7K0pZdY2F0DQyAGM)
> 
> I am using the following code
> 
> show_preview=st.checkbox('Preview',key='Examples') event_example = st_file_browser('./static/static', key="deep1", show_preview=show_preview, use_static_file_server=True, show_choose_file=True, show_delete_file=True, show_download_file=False, show_new_folder=True, show_upload_file=True, static_file_server_path='http://localhost:8000' )

Hi, you can add the flag `--pin-root` to the command like this `./static_file_server/gohttpserver -r ./ -p 8000 --pin-root`:
<img width="819" alt="image" src="https://github.com/pragmatic-streamlit/streamlit-file-browser/assets/28889103/6e671572-348e-4f23-9f62-df85e24d1d85">

And then, `gohttpserver` needs an `access` parameter to enable other features:
```
    import streamlit as st
    from streamlit_file_browser import st_file_browser
    st.set_page_config(layout='wide')
    
    access_all = 0
    access_upload = 0b10000000
    access_delete = 0b01000000
    access_folder = 0b00100000
    access_download = 0b00010000
    access_archive = 0b00001000
    access_preview = 0b00000100
    
    access_all |= access_upload
    access_all |= access_delete
    access_all |= access_folder
    access_all |= access_download
    access_all |= access_archive
    access_all |= access_preview
    
    print(1111, access_all)

    st_file_browser('./',
        key="deep1",
        use_static_file_server=True,
        static_file_server_path=f'http://localhost:8000?access={access_all}',
    )
```
<img width="1431" alt="image" src="https://github.com/pragmatic-streamlit/streamlit-file-browser/assets/28889103/8d712711-d0f6-49be-bb92-33db91d49766">

You can enable those features according to your demand.

The reason we do this is because we want to change user access dynamically. But if you start the `gohttpserver` with a command, it won't be able to control the access dynamically. However, once the access is set with a URL search format, there is a risk because users might pass dangerous access. So, we are using an auth gateway before the `gohttpserver`.

You can refer to the following code to develop a service for auth, and then forward all traffic that passed the verification:
```python
import jwt
from fastapi import FastAPI, Request, Response
import httpx

app = FastAPI()

SECRET_KEY = "my_secret_key"

def decode_jwt(token: str):
    try:
        decoded_payload = jwt.decode(token, SECRET_KEY, algorithms=["HS256"])
        return decoded_payload
    except jwt.ExpiredSignatureError:
        return "Token has expired"
    except jwt.InvalidTokenError:
        return "Invalid token"


TARGET_URL = "http://localhost:8000" # gohttpserver path

@app.api_route("/{path:path}", methods=["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS", "HEAD"])
async def proxy(request: Request, path: str):
    async with httpx.AsyncClient() as client:
        url = f"{TARGET_URL}/{path}"
        
        if not path.startswith("-/assets") and not path.startswith("-/sysinfo") and path != "favicon.ico":
            token = request.query_params.get("token")
            decode_result = decode_jwt(token)
            request_access = int(decode_result.get("access"))
            if not request_access:
                return Response(content="Access Denied", status_code=403)
            current_access = int(request.query_params.get("access"))
            if request_access != current_access:
                return Response(content="Access Denied", status_code=403)

        method = request.method
        data = await request.body()

        headers = dict(request.headers)
        headers.pop("host", None)

        response = await client.request(
            method=method,
            url=url,
            headers=headers,
            content=data,
            params=request.query_params
        )

        return Response(
            content=response.content,
            status_code=response.status_code,
            headers=dict(response.headers)
        )

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=9999)
```

Then add the `access` and `token` parameters to the url used for auth when calling' st_file_browser '
```
    import streamlit as st
    from streamlit_file_browser import st_file_browser
    st.set_page_config(layout='wide')
    
    access_all = 0
    access_upload = 0b10000000
    access_delete = 0b01000000
    access_folder = 0b00100000
    access_download = 0b00010000
    access_archive = 0b00001000
    access_preview = 0b00000100
    
    access_all |= access_upload
    access_all |= access_delete
    access_all |= access_folder
    access_all |= access_download
    access_all |= access_archive
    access_all |= access_preview
    
    print(1111, access_all)
    
    import jwt
    import datetime
    
    SECRET_KEY = "my_secret_key"
    
    def encode_jwt(payload: dict):
        token = jwt.encode(payload, SECRET_KEY, algorithm="HS256")
        return token


    payload = {
        "access": access_all, 
        "exp": datetime.datetime.now() + datetime.timedelta(hours=1)
    }
    file_server_token = encode_jwt(payload)

    st_file_browser('./',
        key="deep1",
        use_static_file_server=True,
        static_file_server_path=f'http://localhost:9999?access={access_all}&token={file_server_token}',
    )
```

In this way, when the user accesses normally, it can be verified and accessed:
![img_v3_02bb_99aab1d7-08ba-4a06-8cea-c2d89283584g](https://github.com/pragmatic-streamlit/streamlit-file-browser/assets/28889103/bc9a9d84-5e02-45a3-951f-ed89fd71e592)

Once the user wants to obtain some illegal permissions, the authentication service will return 403:
![k9T8DGhULl](https://github.com/pragmatic-streamlit/streamlit-file-browser/assets/28889103/8912c5da-fb54-45ce-8e6c-7385726d8b03)

With this way, you can dynamically give users the permissions you want them to have.

**Comment by y805939188** [comment]
> oh also, is there a way to change the theme of the server? I would like it to match my app

Sorry, we haven’t add any code on the theme. If you want, you can modify the front-end source code of 'gohttpserver' by yourself. Don't worry, it won't be too difficult.

**Comment by y805939188** [comment]
> Oh, also, is there an option to include a refresh button? When I manually add a file to the directory I have to reset the component in streamlit. I usually click the back button and then go back into the folder and the file appears

Once you use the `access` params to upload file or create folder, the front-end will refresh automatically.
