### ISSUE TITLE
ImportError: cannot import name 'st_file_browser'

### ISSUE THREAD

**Issue by dnnxl** [pragmatic-streamlit/streamlit-file-browser#40]
Hi I was trying the following code
````
import streamlit as st
from streamlit_file_browser import st_file_browser

st.header('Default Options')
event = st_file_browser("example_artifacts", key='A')
st.write(event)
````
and got the following error:
````
ImportError: cannot import name 'st_file_browser' from partially initialized module 'streamlit_file_browser' (most likely due to a circular import)
````

Do you know what it could be? Thanks.

**Comment by y805939188** [comment]
> Hi I was trying the following code
> 
> ```
> import streamlit as st
> from streamlit_file_browser import st_file_browser
> 
> st.header('Default Options')
> event = st_file_browser("example_artifacts", key='A')
> st.write(event)
> ```
> 
> and got the following error:
> 
> ```
> ImportError: cannot import name 'st_file_browser' from partially initialized module 'streamlit_file_browser' (most likely due to a circular import)
> ```
> 
> Do you know what it could be? Thanks.

Sorry, I cannot replicate this problem. Maybe, you can check if there are circular references in your environment, or provide more detailed code and context for me.
